--- #YAML:1.1
name:              Text-CSV_XS
version:           0.61
abstract:          Comma-Separated Values manipulation routines
license:           perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:      Author
distribution_type: module
provides:
    Text::CSV_XS:
        file:      CSV_XS.pm
        version:   0.61
requires:     
    perl:          5.005
    DynaLoader:    0
    IO::Handle:    0
build_requires:
    perl:          5.005
    Config:        0
    Test::Harness: 0
    Test::More:    0
    Tie::Scalar:   0
resources:
    license:       http://dev.perl.org/licenses/
meta-spec:
    version:       1.4
    url:           http://module-build.sourceforge.net/META-spec-v1.4.html
